version: '3.7'
services:
  mysql_db_container:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: w6%@AJ9n%cl5
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3307:3306"
  back_container:
    restart: always
    image: openjdk:16-alpine
    volumes:
      - ./jars:/app
    working_dir: /app
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    command: "java -jar demo-0.0.1-SNAPSHOT.jar"
    depends_on:
      - mysql_db_container
    ports:
      - "8086:8080"